print ("    *    ")
print ("   * *   ")
print ("  *   *  ")
print (" *     * ")
print ("***   ***")
print ("  *   *  ")
print ("  *   *  ")
print ("  *   *  ")
print ("  *****  ", end="")
print ("Fatto io")

